export const DEPARTMENT_SUBJECTS = {
  "CSE": [
    "Java",
    "Web Development",
    "Data Structures",
    "Database Management",
    "Operating Systems",
    "Computer Networks",
    "Artificial Intelligence",
  ],
  "CSE (AI & ML)": [
    "Python & Machine Learning",
    "Deep Learning",
    "Data Structures",
    "Computer Vision",
    "Natural Language Processing",
  ],
  "CSE (Data Science)": [
    "Data Analysis & Visualization",
    "Big Data Technologies",
    "Database Management",
    "Statistical Foundations",
    "Machine Learning",
  ],
  "IT": [
    "Web Development",
    "Cloud Computing",
    "Cyber Security",
    "Database Management",
    "Operating Systems",
  ],
  "ECE": [
    "Digital Signal Processing",
    "Microprocessors & Microcontrollers",
    "VLSI Design",
    "Analog Electronics",
    "Signals & Systems",
  ],
  "EEE": [
    "Power Systems",
    "Control Systems",
    "Electrical Machines",
    "Power Electronics",
    "Electromagnetic Fields",
  ],
  "ME": [
    "Thermodynamics",
    "Fluid Mechanics",
    "Machine Design",
    "Manufacturing Technology",
    "Kinematics of Machinery",
  ],
  "CE": [
    "Structural Analysis",
    "Geotechnical Engineering",
    "Fluid Mechanics",
    "Surveying & Geomatics",
    "Transportation Engineering",
  ],
  "Chemical": [
    "Chemical Reaction Engineering",
    "Mass Transfer Operations",
    "Heat Transfer",
    "Process Dynamics & Control",
  ],
  "Biotechnology": [
    "Cell Biology & Genetics",
    "Biochemistry",
    "Immunology",
    "Molecular Biology",
  ],
};
